### ISSUE TITLE
Typo in "instance-type" input variable name

### ISSUE THREAD

**Issue by Danleb** [rogisolorzano/github-runner-ec2-start#1]
It is stated in documentation that the name of the variable that controls EC2 instance type is "instance-type", but code uses "ec2-instance-type" name.

Variable name in config:
https://github.com/rogisolorzano/github-runner-ec2-start/blob/d8748e81e16f58fea2f6d2aa6c666478b94ac291/action.yml#L40

Variable name in code:
https://github.com/rogisolorzano/github-runner-ec2-start/blob/d8748e81e16f58fea2f6d2aa6c666478b94ac291/src/config.ts#L23

Please make variable name consistent.

**Comment by rogisolorzano** [comment]
Good catch, thanks. This has been fixed in release v1.1

You can update your workflow to reference that version
```
uses: rogisolorzano/github-runner-ec2-start@v1.1
```

Let me know if you run into any other issues.
